Post/config/routes.rb
Post::Application.routes.draw do

  resources :my_posts, :except=>[:index,:create, :new, :edit, :show, :update, :destroy ] do
    member do
      get "post_show"
      get "post_edit"
      put "post_update"
      delete "post_delete"
      get  "add_comment"
    end

    collection do
      get "post_index"
      get "post_add"
      post "post_create"
    end

  end

  root :to => 'my_posts#post_index'

end

Post/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :my_post
  attr_accessible :comment
 validates :comment, :presence => true
end

Post/app/models/my_post.rb
class MyPost < ActiveRecord::Base
  attr_accessible :description, :name, :title
  validates :name, :description, :title, :presence => true
  has_many :comments

end

Post/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Post/app/controllers/my_posts_controller.rb
class MyPostsController < ApplicationController

  def post_index

    @my_posts = MyPost.paginate(:page => params[:page], :per_page => 5)

  end

  def post_add

    @my_post = MyPost.new()
    @url = post_create_my_posts_path
  end

  def post_create

    @my_post = MyPost.new(params[:my_post])
    @url = post_create_my_posts_path



        respond_to do |format|
          if @my_post.save
            format.html { redirect_to root_path, :notice => 'User was successfully added!!!' }

          else
            format.html { render :action => "post_add" }

        end
       end


  end

  def post_show

    @my_post = MyPost.find(params[:id])
    @comments = @my_post.comments.all


  end

  def post_edit


    @my_post = MyPost.find(params[:id])
    logger.info @my_post.inspect
    @url = post_update_my_post_path

  end

  def post_update

    @my_post = MyPost.find(params[:id])
    @url = post_update_my_post_path


    #if  @my_post.update_attributes(params[:my_post])
    #     redirect_to post_show_my_post_path, :notice => 'Post was successfully updated!!!'
    #  else
    #     render :action => "post_edit"
    #  end

    respond_to do |format|
      if @my_post.update_attributes(params[:my_post])
        format.html { redirect_to post_show_my_post_path, :notice => 'Post was successfully updated!!!' }

      else
        format.html {  render :action => "post_edit" }

      end
    end


  end


  def post_delete

    @my_post = MyPost.find(params[:id])
    @my_post.destroy()

    redirect_to root_path
  end

  def add_comment
    @my_post = MyPost.find(params[:id])


    @comment = @my_post.comments.new(:comment => params[:text])
    @comment.save
    @comments = @my_post.comments.all

    logger.info @comments.inspect

    respond_to do |format|
      format.js
    end

    end



  #def delete_comment
  #  @my_posts = MyPost.find(params[:id])
  #  @comment = @my_posts.comments.all
  #  @comments = @comments.find(params[:id])
  #
  #  if @comments.destroy()
  #    render :action => "post_show"
  #  else
  #    puts "hiiii"
  #  end
  #end


end

Post/app/helpers/application_helper.rb
module ApplicationHelper
end

Post/app/helpers/my_postcontroller_helper.rb
module MyPostcontrollerHelper
end

Post/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Post" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Post</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <ul class="nav nav-list">

                <li>
                  <a href="/">
                    <i class="icon-home"></i>
                    <B>Home</B>
                  </a>
                </li>
                <ul class="nav nav-list">

                  <li>
                     <%= link_to 'Back', root_path %>
                   </li>

                </ul>
              </ul>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <!--<div class="span3">-->
              <!--<div class="well sidebar-nav">-->
                <!--<h3>Sidebar</h3>-->
                <!--<ul class="nav nav-list">-->
                  <!--<li class="nav-header">Sidebar</li>-->
                  <!--<li><%= link_to "Link1", "/path1"  %></li>-->
                  <!--<li><%= link_to "Link2", "/path2"  %></li>-->
                  <!--<li><%= link_to "Link3", "/path3"  %></li>-->
                <!--</ul>-->
              <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
            <!--</div>&lt;!&ndash;/span&ndash;&gt;-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <!--<p>&copy; Company 2012</p>-->
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

Post/app/views/my_posts/_comment.html.erb
<h4>Comments :</h4>


<% @comments.each do |comment|%>
   <p><%= comment.comment %></p>




<% end %>

Post/app/views/my_posts/_form.html.erb
<%= form_for(@my_post, :url => @url) do |i| %>
    <% if @my_post.errors.any? %>
        <div class="alert alert-error">

        <div id="error_explanation">
          <h2><%= pluralize(@my_post.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @my_post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

        </div>
    <% end %>


    <%= i.label :Name  %><br />
    <%= i.text_field :name %> <br>


    <%= i.label :Title %><br />
    <%= i.text_field :title %> <br>

    <%= i.label :Description %><br/>
    <%= i.text_area :description , :rows => 3 %><br>



   <%= i.submit :class => "btn btn-primary" %>
<% end  %>

Post/app/views/my_posts/add_comment.js.erb
$("#abc").html("<%= escape_javascript(render("comment")) %>");

Post/app/views/my_posts/post_add.html.erb
<h5> Post Form</h5>
<%= render 'form' %>
<!--<%= link_to 'Back', root_path %>  -->

Post/app/views/my_posts/post_edit.html.erb
<h4>Edit User Information</h4>
<%= render 'form' %>
<!--<%= link_to 'Back', root_path %>  -->

Post/app/views/my_posts/post_index.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html"><%= notice %></p>

<div class="hero-unit">
  <h1>Welcome</h1>
    <p>Click <%= link_to 'Add Post ', post_add_my_posts_path %>to add new post  </p >

</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th> Name        </th>
    <th>Action </th>
    <!--<th>Action2 </th>-->
    <!--<th>Action3 </th>-->
    <!--<th>Action4 </th>-->
    <!--<th>Action5 </th>-->
  </tr>
  </thead>
  <tbody>


  <% @my_posts.each do |post|%>
      <tr>
        <td><%= post.name %></td>
        <td>
        <div class="btn-group">
          <%= link_to 'Show Post',post_show_my_post_path(post), :class => "btn" %>
          <%= link_to 'Edit Post',post_edit_my_post_path(post), :class => "btn"%>
          <%= link_to 'Delete Post',post_delete_my_post_path(post), :method => :delete, :class => "btn"%>

        </div>
        </td>



        <!--<td><%= link_to 'Add Comment',post_show_my_post_path(post)%> </td>-->
        <!--<td><%= link_to 'Show Comment',post_show_my_post_path(post)%> </td>-->
        <!-- <td><%= link_to 'Delete Comment',post_show_my_post_path(post)%> </td>       -->
      </tr>
  <% end %>

  </tbody>
</table>

<br> <br>

<ul class="pager">
  <%= will_paginate @my_posts %>
</ul>

Post/app/views/my_posts/post_show.erb
<p id = "notice" ><%= notice %></p>

<table class="table table-striped">

  <tr>
<p>
  <b>Name : </b>
  <%= @my_post.name %>
</p>
<br>
<p>
  <b>Title : </b>
  <%= @my_post.title %>
</p>
 <br>
<p>
  <b>Description : </b>
  <%= @my_post.description %>
</p>
  <br>

<div id = "abc" >
  <%= render :partial => "comment"%>

</div>
   </tr>
   <tr>
 <br><br><br>
<div class = "tabbable tabs-left " >
<%= form_for( @my_post.comments.new, :url =>  add_comment_my_post_path) do |i| %>




        <b><%= i.label :comment  %></b><br />
        <%= i.text_area :comment, :rows => 3 %> <br>

        <button id = "add_comment" data-loading-text = "Add Comment" class = "btn btn-primary">Add Comment</button>

      <!--<input type = button value="Add Comment" id = "add_comment">-->
      <!-- <%= i.submit %>  -->
      <!--<button class="btn" data-toggle="button" value="Add Comment" id = "add_comment"></button>-->


<% end %>
 </div>


    </tr>


</table>

<!--<br>-->
<!--<%= link_to 'Back', root_path %>-->